name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # Adjusted for broader compatibility

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: app/backend/package-lock.json
    - run: npm ci
      working-directory: ./app/backend
    - run: npm run build --if-present
      working-directory: ./app/backend
    - run: npm test
      working-directory: ./app/backend

    - run: ls -la app/frontend/
    - run: ls -la app/backend/

  build-frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # Ensuring compatibility

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: app/frontend/package-lock.json
    - run: npm ci
      working-directory: ./app/frontend
    - run: npm run build --if-present
      working-directory: ./app/frontend
